-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 14:09:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
DELIMITER //


CREATE PROCEDURE edt_treat2()
BEGIN

    DECLARE myvar mediumtext ;

-- Assigning the string to the variable
    SET myvar = (SELECT EDT_schedule  FROM edt);
    SELECT SUBSTRING_INDEX(myvar ,'\r\n',3) AS newr;
END //
DELIMITER ;

CALL edt_treat2();

CREATE DATABASE IF NOT EXISTS `Carpool`  /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;

use mysql;
CREATE USER 'admin_carpool'@'localhost' identified by 'Pa$$w0rd';
USE `Carpool` ;
GRANT ALL PRIVILEGES ON Carpool TO 'admin_carpool'@'localhost';

-- -----------------------------------------------------
-- Table `Carpool`.`EDT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carpool`.`EDT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `EDT_schedule` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idEDT_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carpool`.`Places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carpool`.`Places` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Place_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Place_name_UNIQUE` (`Place_name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carpool`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carpool`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teacher_firstname` VARCHAR(45) NOT NULL,
  `teacher_lastname` VARCHAR(45) NOT NULL,
  `teacher_Password` VARCHAR(45) NOT NULL,
  `teacher_car_seats` INT(4) NOT NULL,
  `teacher_email` VARCHAR(200) NOT NULL,
  `Places_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `teacher_email_UNIQUE` (`teacher_email` ASC) ,
  INDEX `fk_teachers_Places1_idx` (`Places_id` ASC) ,
  CONSTRAINT `fk_teachers_Places1`
    FOREIGN KEY (`Places_id`)
    REFERENCES `Carpool`.`Places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carpool`.`Carpooling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carpool`.`Carpooling` (
  `id` INT NOT NULL,
  `Carpooling_time` DATETIME NOT NULL,
  `Carpolling_3/4` TINYINT(2) NOT NULL,
  `Driver_id` INT NOT NULL,
  `Driver_validate` VARCHAR(45) NOT NULL,
  `Places_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Carpooling_teachers_idx` (`Driver_id` ASC),
  INDEX `fk_Carpooling_Places1_idx` (`Places_id` ASC) ,
  CONSTRAINT `fk_Carpooling_teachers`
    FOREIGN KEY (`Driver_id`)
    REFERENCES `Carpool`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carpooling_Places1`
    FOREIGN KEY (`Places_id`)
    REFERENCES `Carpool`.`Places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carpool`.`teachers_has_Carpooling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carpool`.`teachers_has_Carpooling` (
  `teachers_id` INT NOT NULL,
  `Carpooling_id` INT NOT NULL,
  `teacher_validation` TINYINT(2) NOT NULL,
  PRIMARY KEY (`teachers_id`, `Carpooling_id`),
  INDEX `fk_teachers_has_Carpooling_Carpooling1_idx` (`Carpooling_id` ASC),
  INDEX `fk_teachers_has_Carpooling_teachers1_idx` (`teachers_id` ASC) ,
  CONSTRAINT `fk_teachers_has_Carpooling_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `Carpool`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teachers_has_Carpooling_Carpooling1`
    FOREIGN KEY (`Carpooling_id`)
    REFERENCES `Carpool`.`Carpooling` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carpool`.`EDT_has_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carpool`.`EDT_has_teachers` (
  `EDT_id` INT NOT NULL,
  `teachers_id` INT NOT NULL,
  `Starting_hour` DATETIME NOT NULL,
  `Finnishing_hour` DATETIME NOT NULL,
  PRIMARY KEY (`EDT_id`, `teachers_id`),
  INDEX `fk_EDT_has_teachers_teachers1_idx` (`teachers_id` ASC) ,
  INDEX `fk_EDT_has_teachers_EDT1_idx` (`EDT_id` ASC) ,
  CONSTRAINT `fk_EDT_has_teachers_EDT1`
    FOREIGN KEY (`EDT_id`)
    REFERENCES `Carpool`.`EDT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EDT_has_teachers_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `Carpool`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
